### ISSUE TITLE
Generate the highly scalable router using react-router-dom

### ISSUE THREAD

**Issue by MqrcosT** [React-Open-Dash/react-open-dashboard#15]

**Comment by carlosbajo** [comment]
You're fast dude! I will share with you a link later about how you can implement this, but you are free to start looking on the internet.

**Comment by carlosbajo** [comment]
I used this link in the past to implement this router https://www.ryanjyost.com/react-routing/, the code it's a bit older, you will have to check and update some parts of the code, but you can take the post as a guide. @MqrcosT - good look with this, feel free to ask anything.
